### ISSUE TITLE
Move this to pandas-dev?

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas-docs-travis#1]

**Comment by jorisvandenbossche** [comment]
+1 

(supposing that github does set-up redirects?)

**Comment by wesm** [comment]
I think so. The Travis CI would probably have to be set up again

**Comment by jreback** [comment]
yep sure
and esp since this is broken because of the token issue

**Comment by wesm** [comment]
it's done

**Comment by jorisvandenbossche** [comment]
Redirecting is apparently not working

https://pandas-dev.github.io/pandas-docs-travis/whatsnew.html as new url now works 
https://pandas-docs.github.io/pandas-docs-travis/whatsnew.html old url does not work anymore

**Comment by jorisvandenbossche** [comment]
Looking at https://help.github.com/articles/about-repository-transfers/

> If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, we don't redirect GitHub Pages associated with the repository.

I don't fully understand the first part (what have links to the git repo to do with github pages site?), but second part seems to indicate that we should not expect redirects

**Comment by jorisvandenbossche** [comment]
If that is the case, not sure this move is worth it, and I would personally move it back .. 
(the links to the dev docs are used quite a bit in the worldwide web)

**Comment by jreback** [comment]
maybe email github and see if they can fix?

**Comment by jorisvandenbossche** [comment]
Possibly, but since it is explicitly in their docs, not sure they will want to do otherwise for us. 

Anyhow, for now I would just move it back until we have a solution for redirects. As this will break a lot of links.

**Comment by jorisvandenbossche** [comment]
I moved this back for now.

**Comment by jreback** [comment]
@jorisvandenbossche I think permissions are messed up here. I can't even access setting any longer; I think @TomAugspurger needs permissions too.

**Comment by jorisvandenbossche** [comment]
When I moved it back, github asked me to add it to the two teams. Which it has done, but apparently only with read rights ? 
In any case, I cannot change any settings about that there, I think a maintainer (= @wesm) has to do this

**Comment by wesm** [comment]
I just gave you all admin on the repo. I'm not sure why the permissions were messed up
